import stripe
from django.http import HttpResponse
from django.conf import settings
from mysite.forms import ContactForm
from django.core.mail import EmailMessage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
import pandas as pd
from .models import Produktai
from sqlalchemy import create_engine
from sqlalchemy import text
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

engine = create_engine('postgresql://postgres:[]@localhost:5432/postgres')
conn= engine.connect()

def get_products():
    prods=pd.DataFrame(conn.execute(text("SELECT * FROM fixjob.produktai")).fetchall())

    return prods.to_dict(orient='records')


def products(request):
    items_per_page = 12
    page = request.GET.get('page', 1)

    # Assuming prods is your queryset
    prods = get_products()
    paginator = Paginator(prods, items_per_page)
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        # If the page is not an integer, deliver the first page.
        items = paginator.page(1)
    except EmptyPage:
        # If the page is out of range (e.g., 9999), deliver the last page.
        items = paginator.page(paginator.num_pages)

    context = {
        'items': items,
    }

    return render(request, 'prods.html', context)


def product_detail(request, id):
    DATABASE_URL = "postgresql://postgres:[]@localhost:5432/postgres"
    # Create engine
    engine = create_engine(DATABASE_URL)
    # Create a session
    Session = sessionmaker(bind=engine)
    query = text('SELECT * FROM fixjob.produktai WHERE "ID" = :id')  # Use double quotes
    params = {"id": id}


    with Session() as session:
        result = session.execute(query, params)
        product = result.mappings().first()


    #pro = get_products()[id]
    context={'obj':product}
    return render(request, 'product_info.html',context)


class PostListView(View):
    def get(self, request):
        posts_per_page = 4
        posts = Post.objects.all().order_by('-id')
        paginator = Paginator(posts, posts_per_page)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'product_list.html', {'page_obj': page_obj})

def index(request):
    data = {}
    return render(request, 'index.html', data)


def payment(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    publishable_key = settings.STRIPE_PUBLISHABLE_KEY
    token = None

    if request.method == 'POST':
        token = request.POST.get('stripeToken')  # Get the token generated by Stripe.js
    amount = 100  # Get the amount from the form or model
    button_amount = amount*100
    currency = 'eur'  # Get the currency from the form or model

    description = "USB raktas"
    item_desc = 'Mikroschema, kuria galima panaudoti perkelti duomenis is vienos saugojamos vietos i kita.'
    if token:
        try:
                # Create a charge using the token
            charge = stripe.Charge.create(
                amount= amount*100,  # Amount in cents
                currency=currency,
                description=description,
                source=token,
            )
            return render(request, 'success.html')
        except stripe.error.CardError as e:
            # Display an error message to the user
            return render(request, 'error.html', {'error': e.error.message})

    return render(request, 'payment.html', {'pub_key':publishable_key, 'amount':amount, 'desc':description,'cur':currency, 'item_desc':item_desc, 'but':button_amount})


def success(request):
    return render(request, 'success.html')
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message'] + "  "+ form.cleaned_data['phone']
            subject= form.cleaned_data['subject']


            EmailMessage(
               '{} Žinutė iš kontaktų formos nuo {}'.format(name, subject),
               message,
               'info@fixjob.lt', # Send from (your website)
               ['mbfixjob@gmail.com'], # Send to (your admin email)
               [],
               reply_to=[email] # Email from the form to get back to
           ).send()

            return render(request, 'contact_success.html')
    else:
        form = ContactForm()
    return render(request, 'susisiekti.html', {'form': form})




def product_list(request):
    return render(request, 'product_list.html')

def grindys(request):
    return render (request, 'grindys.html')

def paslaugos(request):
    return render(request, 'paslaugos.html')

