# Generated by Django 4.2.11 on 2024-05-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'main_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainKategorija',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'main_kategorija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pavadinimas', models.CharField(max_length=255)),
                ('turinys', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('foto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainPostKategorija',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'main_post_kategorija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainPostTags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'main_post_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainProduktai',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url_to_product', models.CharField(max_length=255)),
                ('category_path', models.CharField(max_length=255)),
                ('url_to_image', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('sales', models.IntegerField()),
                ('review_rate', models.FloatField()),
                ('estimated_commission_rate', models.FloatField()),
                ('estimated_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_country_name_url_to_product_categorypath_url_to_image_curren', models.CharField(blank=True, db_column='ID;Country;Name;URL to product;categoryPath;URL to image;Curren', max_length=1024, null=True)),
            ],
            options={
                'db_table': 'main_produktai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'main_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produktai',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('url_to_product', models.TextField(blank=True, db_column='URL to product', null=True)),
                ('categorypath', models.TextField(blank=True, db_column='categoryPath', null=True)),
                ('url_to_image', models.TextField(blank=True, db_column='URL to image', null=True)),
                ('currency', models.TextField(blank=True, db_column='Currency', null=True)),
                ('sales', models.FloatField(blank=True, db_column='Sales', null=True)),
                ('review_rate', models.FloatField(blank=True, db_column='Review Rate', null=True)),
                ('estimated_commission_rate', models.TextField(blank=True, db_column='Estimated Commission Rate', null=True)),
                ('estimated_earnings', models.FloatField(blank=True, db_column='Estimated Earnings', null=True)),
            ],
            options={
                'db_table': 'produktai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProduktaiLt',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('salis', models.TextField(blank=True, null=True)),
                ('pavadinimas', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('kategirija', models.TextField(blank=True, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('valiuta', models.TextField(blank=True, db_column='Valiuta', null=True)),
                ('pardavimai', models.TextField(blank=True, db_column='Pardavimai', null=True)),
                ('vertinimas', models.TextField(blank=True, null=True)),
                ('numatomas_komisinis_dydis', models.TextField(blank=True, db_column='Numatomas komisinis dydis', null=True)),
                ('uzdarbis', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produktai_lt',
                'managed': False,
            },
        ),
    ]
